apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkinservice
  name: jenkinservice
  # namespace: default
spec:
  ports:
  - name: 8080-8081
    port: 8080
    protocol: TCP
    targetPort: web
    nodePort: 30003 
    # targetPort: 8081
  - name: agent
    port: 5000
    targetPort: agent
  selector:
    app: jenkinstest1
  type: NodePort
status:
  loadBalancer: {}

